### ISSUE TITLE
Selection cleared in vim mode

### ISSUE THREAD

**Issue by maxim** [yaroslavyaroslav/OpenAI-sublime-text#50] opened 2024-05-07 22:36 UTC
When using vim mode (NeoVintageous in my case), I cannot get the message to apply to my selection. When I select something, then go to New Message, the selection clears, and no context is sent to ChatGPT. It works only if I use vim's visual select mode.

https://github.com/yaroslavyaroslav/OpenAI-sublime-text/assets/7758/7c31818a-6275-45c4-bcb4-fe5c8a64dcf5

P.S. This is on latest version (4.0.0)

**Comment by yaroslavyaroslav** [comment] 2024-05-07 22:43
And what's the assistant mode is used here (panel, append, insert, edit)?

And to clarify neovim is the package, right?

**Comment by maxim** [comment] 2024-05-08 20:41
@yaroslavyaroslav The mode is "replace", the package for vim mode is [NeoVintageous](https://packagecontrol.io/packages/NeoVintageous), and I select by switching to insert mode (`i`) and pressing or shift+up, shift+down.

**Comment by yaroslavyaroslav** [comment] 2024-05-08 22:31
Yeah, now I'm able to reproduce that, but luckily 😅 the problem is not on my side. NeoVintageous drops selection on a focus change in that particular case. And this is exactly what happening when input panel appears from the bottom. So at the time when plugin reads from a buffer selection it's empty, nothing to say about the time when it's starting to write.

You could check it yourself by switching between two groups from one to another and then to compare it with (`v`) selection behaviour.

So I'm afraid I could only suggest you to raise this issue in their repo, I mean if it's not the desired behaviour in this mode ofc (not into vim stuff).

**Comment by maxim** [comment] 2024-05-09 14:24
Makes sense, I posted [an issue](https://github.com/NeoVintageous/NeoVintageous/issues/1020) there. 🤞🏻

**Comment by yaroslavyaroslav** [comment] 2024-05-09 15:53
Closing this so far.

**Closed by yaroslavyaroslav** 2024-05-09 15:53 UTC
